# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HYU_TT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HYU_TT
  platform :ios, '10.2'
  pod 'CurriculaTable'
  pod 'SQLite.swift', '~> 0.11.3'

  target 'HYU_TTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WidgetTest' do
  end
  
end

